linters:
  disable:
    - unused
linters-settings:
  unused:
    field-writes-are-uses: false
    exported-fields-are-used: false
    exported-is-used: false
issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA4023"
