---
apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
    - image: registry.cn-hangzhou.aliyuncs.com/acs/ack-ram-tool:1.0.0
      imagePullPolicy: "Always"
      args:
        - rrsa
        - demo
      name: test
      env:
        - name: ALIBABA_CLOUD_ROLE_ARN
          value: <role_arn>
        - name: ALIBABA_CLOUD_OIDC_PROVIDER_ARN
          value: <oidc_arn>
        - name: ALIBABA_CLOUD_OIDC_TOKEN_FILE
          value: /var/run/secrets/rrsa/oidc-token
      volumeMounts:
        - mountPath: /var/run/secrets/rrsa
          name: rrsa-oidc-token
  serviceAccountName: sa-abc
  restartPolicy: Never
  volumes:
    - name: rrsa-oidc-token
      projected:
        sources:
          - serviceAccountToken:
              path: oidc-token
              expirationSeconds: 7200
              audience: "sts.aliyuncs.com"
