---
apiVersion: v1
kind: Namespace
metadata:
  name: rrsa-demo
  labels:
    pod-identity.alibabacloud.com/injection: enabled

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: rrsa-demo
  annotations:
    pod-identity.alibabacloud.com/role-name: test-rrsa-demo

---
apiVersion: batch/v1
kind: Job
metadata:
  name: demo
  namespace: rrsa-demo
spec:
  template:
    spec:
      serviceAccountName: demo-sa
      restartPolicy: Never
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/acs/ack-ram-tool:1.0.0
          imagePullPolicy: "Always"
          args:
            - rrsa
            - demo
            - --no-loop
          name: test
