---
apiVersion: v1
kind: Namespace
metadata:
  name: rrsa-demo-oss-nodejs-sdk
  labels:
    pod-identity.alibabacloud.com/injection: 'on'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: rrsa-demo-oss-nodejs-sdk
  annotations:
    pod-identity.alibabacloud.com/role-name: test-rrsa-demo

---
apiVersion: batch/v1
kind: Job
metadata:
  name: demo
  namespace: rrsa-demo-oss-nodejs-sdk
spec:
  template:
    spec:
      serviceAccountName: demo-sa
      restartPolicy: Never
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/acs/ack-ram-tool:1.0.0-rrsa-example-oss-nodejs
          imagePullPolicy: "Always"
          name: test
