---
apiVersion: v1
kind: Namespace
metadata:
  name: rrsa-demo-ossutil
  labels:
    pod-identity.alibabacloud.com/injection: 'on'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: rrsa-demo-ossutil
  annotations:
    pod-identity.alibabacloud.com/role-name: test-rrsa-demo

---
apiVersion: batch/v1
kind: Job
metadata:
  name: demo
  namespace: rrsa-demo-ossutil
spec:
  template:
    spec:
      serviceAccountName: demo-sa
      restartPolicy: Never
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/acs/ack-ram-tool:1.0.0-dev
          imagePullPolicy: "Always"
          name: server
          command:
            - ack-ram-tool
            - export-credentials
            - --serve
            - 0.0.0.0:8088
        - image: registry.cn-hangzhou.aliyuncs.com/acs/ack-ram-tool:1.0.0-dev-rrsa-example-ossutil
          imagePullPolicy: "Always"
          name: test
